### ISSUE TITLE
MSBuild SDK 2.2.x location path incorrect

### ISSUE THREAD

**Issue by agc93** [tintoy/msbuild-project-tools-server#16]
This is basically just a reappearance of the bug from [msbuild-project-tools-vscode#46](https://github.com/tintoy/msbuild-project-tools-vscode/issues/46) but since I don't have 3.x installed, it might be a little different.

---

Opening a `.csproj` file on Fedora 29 with .NET Core 2.2.203 installed results in a syntax error being reported in the `csproj` with the following message:

```
The imported project "/usr/share/dotnet/sdk/2.2.203/15.0/Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. /tmp/test/test.csproj(MSB4019)
```

At least on my machine, the `Microsoft.Common.props` file is actually in `/usr/share/dotnet/sdk/2.2.203/Current/Microsoft.Common.props` rather than the `15.0` the [extension looks for in any version below 3.x](https://github.com/tintoy/msbuild-project-tools-server/blob/master/src/LanguageServer.Common/Utilities/MSBuildHelper.cs#L95).

Is this perhaps a change in 2.2.x?

---

I just tried a fresh .NET Core 2.2.203 install into an Ubuntu 18.10 container and it was also installed into `/usr/share/dotnet/sdk/2.2.203/Current`, not `15.0`.

I'm guessing this is a change in 2.2.x, but I don't have a Windows machine handy to check.

Let me know if you need more info or testing.

**Comment by tintoy** [comment]
Hi - thanks for reporting! Yes, I suspect they've changed the behaviour _again_ :-/

I'll have a look shortly and let you know what I find :)

**Comment by tintoy** [comment]
Turns out they changed that behaviour sometime _before_ 2.2. I've modified the version check to take this into account.

Could you try out this new VSIX and let me know if it works for you?

[msbuild-project-tools-0.2.55.vsix.zip](https://github.com/tintoy/msbuild-project-tools-server/files/3175774/msbuild-project-tools-0.2.55.vsix.zip)

**Comment by agc93** [comment]
Sorry it took so long to test, but I've just tried that new VSIX and things look to be good. That error seems to be gone, and extension features still seem to be working fine!

Thanks for the quick fix!
