### ISSUE TITLE
Upgrade to .NET Core 3.0

### ISSUE THREAD

**Issue by tintoy** [tintoy/msbuild-project-tools-server#17]
Now that 3.0 is out, we should upgrade the language server to target `netcoreapp3.0`.

This means consumers will need either the 3.0 SDK or the 3.0 runtime if they don’t want to upgrade to the 3.0 SDK yet.

May need to be careful about verifying that this doesn’t affect behaviour of the MSBuild engine at runtime.

**Comment by tintoy** [comment]
Should help with tintoy/msbuild-project-tools-vscode#42.

**Comment by tintoy** [comment]
https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.3.1

Hi - @divinebovine @mateusdeap, are you able to try this new build to see if it works for you? It's now built against .NET Core 3.x.

**Comment by divinebovine** [comment]
@tintoy should it be showing up when I try to check for extension updates in vscode? Because it doesn't show up. Or do I need to install it by VSIX?

**Comment by tintoy** [comment]
By VSIX - I want to make sure it actually works for others before I publish it more widely :)

**Comment by tintoy** [comment]
In the meanwhile I'm going to try to enhance the extension as well so it can do a better job of reporting when the language server can't be launched.

**Comment by tintoy** [comment]
Published [v0.3.2](https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.3.2) - the extension should now provide more useful information if the language server cannot be started.

**Comment by mateusdeap** [comment]
@tintoy Ok, so I tested the extension. Everything seems to be just fine. I just had one issue, but I'm unsure if it's a bug:
![msbuild_test](https://user-images.githubusercontent.com/14188887/68089556-d5d33580-fe48-11e9-8617-d5a9cf2e7231.png)
If I just type the `<` character, it will give me the snippets, however it will just concatenate the snippet to the `<` I typed, as the image shows

**Comment by MeikTranel** [comment]
That's been an issue for quite some time now. Should be unrelated to .NET Core 3.0

**Comment by tintoy** [comment]
Sorry, this one has fallen off radar :)

I’ll look into it this afternoon...

**Comment by MeikTranel** [comment]
No worries mate. Just wanted let you know before you go yak shaving on .NET Core 3.0  for no reason 😄

**Comment by tintoy** [comment]
Here's what happens when I try to insert a `<PackageReference>` snippet:

![Repro](https://user-images.githubusercontent.com/1646284/71759845-a9e73580-2f07-11ea-82b3-4038c5fe573e.gif)

(the only keys I press are `<`, then `P`, then `<enter>`)

**Comment by tintoy** [comment]
That's on VSCode v1.39.2.

**Comment by mateusdeap** [comment]
Hmmm. I guess I'll check my VS Code version later and test it. Either way, I think this issue can be considered closed, since the upgrade has been done. Thanks a bunch! :D
