### ISSUE TITLE
Upgrade to .NET Core 3.1

### ISSUE THREAD

**Issue by tintoy** [tintoy/msbuild-project-tools-server#20]
3.1 is the LTS release and should be good until December 2022.

See official support policy:

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by amshtemp** [comment]
MS is abandoning the old mantra of "let's do little upgrade" and more pushing towards more progressive and rapid updates. IMHO I think msbuild-project-tools-server should follow suit and upgrade to 5.0 too.

**Comment by tintoy** [comment]
Yeah as long as the 5.0 runtime can be installed without affecting people stuck on 3.1 that could be ok but I’ll need to do some research to see how that affects system requirements etc.

**Comment by tintoy** [comment]
For now, I'm going to target `netcoreapp3.1` rather than `net5` since the 3.1 runtime is a much smaller download than the 3.1 SDK.

If we hit any blockers, I'll revisit this but for now it should do a good enough job of spreading the pain out across all of our users 😉

**Comment by tintoy** [comment]
Ok - will publish the VSIX package after I've had more time to do testing. If anyone else needs it sooner, here it is:

[msbuild-project-tools-0.3.11.zip](https://github.com/tintoy/msbuild-project-tools-server/files/5611794/msbuild-project-tools-0.3.11.zip)

**Comment by tintoy** [comment]
(that was pretty painful BTW, I may still consider upgrading to 5.0 if only because there were so many package version conflicts going from 3.0 to 3.1)

**Comment by aneeskodappana** [comment]
@tintoy any updates on `5.0.*` support

**Comment by tintoy** [comment]
Hi - not planning to move over yet; want to see how the current version performs for a while before making another version jump for the runtime :)

**Comment by tintoy** [comment]
(but longer term I hope we can look at moving over sometime in February or March)
