### ISSUE TITLE
2 CI systems

### ISSUE THREAD

**Issue by DoctorKrolic** [tintoy/msbuild-project-tools-server#67]
There are 2 CI systems in place in this repo:
1. AppVeyor: https://github.com/tintoy/msbuild-project-tools-server/blob/master/.appveyor.yml
2. Azure pipelines: https://github.com/tintoy/msbuild-project-tools-server/blob/master/azure-pipelines.yml

i would say this isn't a good thing and it's better to move to 1 CI provider, probably azure one. @tintoy What do you think about this?

**Comment by tintoy** [comment]
Definitely! I haven't had time to disable AppVeyor yet but I'll do that ASAP.

**Comment by tintoy** [comment]
Ack! Meant to do that one as a pull request, but got distracted.

As it turns out, I deleted the corresponding AppVeyor project a while back so all I had to do was delete `appveyor.yml` and we should be good to go!

**Comment by DoctorKrolic** [comment]
Cool!
