### ISSUE TITLE
Settings are verbose

### ISSUE THREAD

**Issue by amshtemp** [tintoy/msbuild-project-tools-server#7]
Whether I change one setting or ten, msbuildProjectTools seems to always inject the full settings in VS Code. even those I didn't modify.

![untitled](https://user-images.githubusercontent.com/35246925/45064235-510d5000-b0bb-11e8-8200-cb23297bf65e.png)

BTW... What a great extension. Can't life wihtou it.

**Comment by tintoy** [comment]
Hi - thanks, glad you find it useful :)

I think this happens because I've specified the defaults too deeply. I won't have time to look at this till tomorrow but I'll have a look then and see what I can do.

**Comment by tintoy** [comment]
(the other issue is that the settings are a nested structure, not a series of dotted strings)

**Comment by amshtemp** [comment]
Found another problem with the current structure.
It shows nothing in the new GUI-based settings editor.
I guess it only recognizes flat dotted settings

**Comment by tintoy** [comment]
Yeah, that's definitely going to be an issue. If I change our settings schema, I need to be careful that I don't lose people's existing settings. It may take a couple of days to create a reliable solution so bear with me :)

PS. Thanks for reporting this - I had no idea that the new settings editor was going to be a problem!

**Comment by tintoy** [comment]
* [ ] TODO: Update language service to handle flattened settings schema.

**Comment by tintoy** [comment]
Will be a day or 2 before I have time to test these changes, but it looks like we can switch to flattened settings without much of a problem :)

**Comment by tintoy** [comment]
Sorry for the delay, I haven't had time to test these changes properly yet. It's Saturday now, so I'm hoping I can test them and create a new release today.

**Comment by tintoy** [comment]
Hmm, the VSCode settings system is proving trickier to deal with than I was expecting. I'll keep working on this but it may take another day or 2 :)

**Comment by tintoy** [comment]
Ok - I've created [v0.2.42](https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.2.42), but I haven't published it to the VS Marketplace yet. Would you be willing to try [manually installing the extension VSIX](https://github.com/tintoy/msbuild-project-tools-vscode/blob/v0.2.38/README.md#installation) (you may need to uninstall the existing extension before doing this) to see if these changes fix your problem?

**Comment by amshtemp** [comment]
Tested it. Seems to work just.
Thanks

**Comment by tintoy** [comment]
Thanks! Ok, I’ll get it published :)

**Comment by tintoy** [comment]
Hi - v0.2.42 has been [published](https://github.com/tintoy/msbuild-project-tools-vscode/releases/tag/v0.2.42) now so I'm going to close this issue, but feel free to reopen it if you still have problems.

Thanks again for taking the time to report it :)
