### ISSUE TITLE
Microsoft.WebApplication.targets was not found

### ISSUE THREAD

**Issue by kenorb** [tintoy/msbuild-project-tools-server#8]
Can't build `.csproj` file due to the following error:

> [project.csproj] The imported project "c:\Users\myuser\.vscode\extensions\tintoy.msbuild-project-tools-0.2.39\out\language-server\Microsoft\VisualStudio\v12.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Failing line:

    <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />

**Comment by tintoy** [comment]
Hmm - it sounds like one of the environment variables used to detect the dotnet / MSBuild location is missing. I'll see what I can dig up (work's pretty crazy today, so I may not get to this until tomorrow - sorry about that).

**Comment by tintoy** [comment]
What do you see when you run `dotnet --info`?

**Comment by tintoy** [comment]
Also, can you open the embedded terminal inside VS Code and (from PowerShell) run `Get-Command msbuild` and post the output of that, too?

**Comment by tintoy** [comment]
BTW, if you don't have Visual Studio installed at all, I you might be missing some of the the targets required to load that project (the fact that the path is relative to `VSToolsPath` makes me think those targets are distributed with Visual Studio). Are you able to build it from the command line with `msbuild project.csproj`?

This might also be a workaround:

https://stackoverflow.com/q/46572317

**Comment by kenorb** [comment]
I've checked and the same happens with `msbuild` it-self.
```
>whereis msbuild
C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe
>msbuild /version
Microsoft (R) Build Engine version 12.0.21005.1
[Microsoft .NET Framework, version 4.0.30319.42000]
>msbuild SL.API.csproj
Microsoft (R) Build Engine version 12.0.21005.1
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 17/09/2018 13:14:00.
Project "D:\Sites\NT\project\src\SL\SL.API\SL.API.csproj" on node 1 (default targets).
D:\Sites\NT\project\src\SL\SL.API\SL.API.csproj(829,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\WebApplications\Microsoft.WebApplicati
on.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "D:\Sites\NT\project\src\SL\SL.API\SL.API.csproj" (default targets) -- FAILED.


Build FAILED.

"D:\Sites\NT\project\src\SL\SL.API\SL.API.csproj" (default target) (1) ->
  D:\Sites\NT\project\src\SL\SL.API\SL.API.csproj(829,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\WebApplications\Microsoft.WebApplica
tion.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.11
```

I'll check the links and see if I can find anything else.

**Comment by kenorb** [comment]
### Windows

Another attempt:

```
scoop install nuget # @see: https://github.com/lukesampson/scoop
nuget restore # In directory with .nuget dir or a solution file.
nuget install # In directory with packages.config
```
It installed some missing packages, but compiling with `msbuild` failed again on the same error.

As for a workaround, I've open the project in Visual Studio 2017, opened a solution file (`.sln`) and it installed all the missing dependencies, and it seems to work now.

**Comment by tintoy** [comment]
Thanks - I'll make a note in case anyone else runs into this.

**Comment by JavierMartinez07** [comment]
I have the same problem @tintoy 


> Can't build `.csproj` file due to the following error:
> 
> > [project.csproj] The imported project "c:\Users\myuser.vscode\extensions\tintoy.msbuild-project-tools-0.2.39\out\language-server\Microsoft\VisualStudio\v12.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the  declaration is correct, and that the file exists on disk.
> 
> Failing line:
> 
> ```
> <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
> ```

**Comment by tintoy** [comment]
Can you tell me a bit about your environment? What OS, version of Visual Studio, .NET Core SDK, etc?

**Comment by JavierMartinez07** [comment]
**ENVIRONMENT**
- OS: Ubuntu 18.4 (server)
- Visual Studio 2019 (local)
- .NET Core 3.1 (server)

I am using github actions to create CICD.
The solution has most projects with .net core 3.1, but I was able to determine that one of them has a class library in .net framework 4.6. Which is giving me this error.

**Comment by tintoy** [comment]
I don’t think you can work with that project type on Linux, unfortunately - from memory they need the full .NET framework, and core will not suffice :-(

**Comment by JavierMartinez07** [comment]
I understand, thanks for the help.

**Comment by tintoy** [comment]
No worries - sorry I couldn’t give you a happier result :-/
