### ISSUE TITLE
[BUG] On Windows, file handles are opened with no FILE_SHARE_* mode, preventing other software (e.g. extensions) from opening those files

### ISSUE THREAD

**Issue by BinToss** [tintoy/msbuild-project-tools-server#82]
I've been frequently noticing `dotnet build` and similar operations complaining about "access denied" and "The process cannot access the file `.../obj/project.assets.json` because it is being used by another process."

Searching for handles with System Informer results in the relevant files only being opened by the dotnet.exe process hosting this extension.
![image](https://github.com/tintoy/msbuild-project-tools-vscode/assets/7243190/36ff4e8c-31b7-4583-b8b8-41ff57a2e9c5)
![image](https://github.com/tintoy/msbuild-project-tools-vscode/assets/7243190/cd22cd8b-d8ef-4099-9a36-1f6682dfa268)
![image](https://github.com/tintoy/msbuild-project-tools-vscode/assets/7243190/7e75facd-0217-4fe3-84cd-ed57e020ed1b)

**Comment by tintoy** [comment]
Published v0.5.3 to the VS extension gallery (it may take a couple of minutes to be come visible) 🙂
